Fonctionnel mais n'utilise pas le bon network

diff --git a/p1/Vagrantfile b/p1/Vagrantfile
--- a/p1/Vagrantfile
+++ b/p1/Vagrantfile
@@ -1,20 +1,22 @@
 Vagrant.configure("2") do |config|
 
   # SERVER CONFIGURATION
-  config.vm.define "server" do |server|
-    server.vm.box = "debian/jessie64"
+  config.vm.define "hbelleS" do |server|
+    server.vm.box = "debian/buster64"
     server.vm.network "private_network", ip: "192.168.56.110", interface: "eth1"
     server.vm.network "forwarded_port", guest: 22, host: 4242, id: "ssh"
-    server.vm.provider "vmware_desktop" do |vmware|
-      vmware.customize ["modifyvm", :id, "--name", "hbelleS"]
-      vmware.gui = true
-      vmware.memory = "1024"
-      vmware.cpus = 1
+    server.vm.provider "virtualbox" do |vb|
+      vb.name = "hbelleS"
+      vb.memory = "1024"
+      vb.cpus = 1
     end
-    server.ssh.insert_key = false
+    server.vm.synced_folder "./shared", "/vagrant", type: "nfs", nfs_version: 4
     server.vm.provision "shell", inline: <<-SHELL
+      set -x
+      sudo apt-get update
+      sudo apt-get install -y curl
       # Installer K3s en tant que serveur maître
-      curl -sSL https://get.k3s.io | sh -
+      curl -sSL https://get.k3s.io | sh -s - server --node-ip 192.168.56.110
       # Copier le fichier kubeconfig pour l'accès externe
       sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/kubeconfig
       # Modifier l'adresse IP dans le fichier kubeconfig
@@ -25,22 +27,37 @@ Vagrant.configure("2") do |config|
   end
 
   # SERVER WORKER CONFIGURATION
-  config.vm.define "serverWorker" do |serverWorker|
-    serverWorker.vm.box = "debian/jessie64"
+  config.vm.define "hbelleSW" do |serverWorker|
+    serverWorker.vm.box = "debian/buster64"
     serverWorker.vm.network "private_network", ip: "192.168.56.111", interface: "eth1"
     serverWorker.vm.network "forwarded_port", guest: 22, host: 4243, id: "ssh"
-    serverWorker.vm.provider "vmware_desktop" do |vmware|
-      vmware.customize ["modifyvm", :id, "--name", "hbelleSW"]
-      vmware.gui = true
-      vmware.memory = "1024"
-      vmware.cpus = 1
+    serverWorker.vm.provider "virtualbox" do |vb|
+      vb.name = "hbelleSW"
+      vb.memory = "1024"
+      vb.cpus = 1
     end
-    serverWorker.ssh.insert_key = false
+    serverWorker.vm.synced_folder "./shared", "/vagrant", type: "nfs", nfs_version: 4
     serverWorker.vm.provision "shell", inline: <<-SHELL
-      # Attendre que le fichier node-token soit disponible
+      set -x
+      echo "Updating package list..."
+      sudo apt-get update
+      echo "Installing curl..."
+      sudo apt-get install -y curl
+      echo "Waiting for node-token file..."
       while [ ! -f /vagrant/node-token ]; do sleep 1; done
-      # Installer K3s en tant qu'agent
-      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/node-token) sh -s - agent
+      echo "node-token file found. Attempting to join the cluster..."
+      K3S_TOKEN=$(cat /vagrant/node-token)
+      echo "K3S_TOKEN: $K3S_TOKEN"
+      while true; do
+        curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$K3S_TOKEN sh -s - agent --node-ip 192.168.56.111 --with-node-id
+        if [ $? -eq 0 ]; then
+          echo "Successfully joined the cluster."
+          break
+        else
+          echo "Failed to join the cluster. Retrying in 2 seconds..."
+          sleep 2
+        fi
+      done
     SHELL
   end
 end
